name: .NET Workflow 4women

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Executa a cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        configuration: [Release]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.1' 

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration ${{ matrix.configuration }} --no-restore

      - name: Run tests
        run: dotnet test --configuration ${{ matrix.configuration }} --no-build --verbosity normal

      - name: Custom Script - Clean up artifacts
        run: |
          echo "Running custom script to clean up artifacts"
          rm -rf ./artifacts
          mkdir ./artifacts
